---

system_packages:
  - python-dev
  - git
  - python-virtualenv
  - g++
  - gcc
  - libpq-dev
  - postgresql
  - postgresql-common
  - postgresql-contrib
  - python-psycopg2
  - vim
  # needed for the ansible apt_repository module
  - python-apt
#  - libsemanage-python

circus_system_packages:
  - libzmq-dev
  - libevent-dev
