---

- name: reload systemd
  sudo: yes
  sudo: yes
  command: systemctl daemon-reload

- name: restart app
  sudo: yes
  service: name=mita state=restarted enabled=yes

- name: restart mita-celery
  service: name=mita-celery state=restarted enabled=yes
  sudo: yes

- name: restart mita-celerybeat
  service: name=mita-celerybeat state=restarted enabled=yes
  sudo: yes
