---

- name: reload systemd
  command: systemctl daemon-reload

- name: restart app
  service:
    name: mita
    state: restarted
    enabled: yes

- name: restart mita-celery
  service:
    name: mita-celery
    state: restarted
    enabled: yes

- name: restart mita-celerybeat
  service:
    name: mita-celerybeat
    state: restarted
    enabled: yes
